import { DocumentType } from "../types/documentsType";

export const hits: DocumentType[] = [
  {
    id: "sEbY0JEBP3pVznhigYUx",
    index: "samed_index",
    filename: "server.cli",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/diff-files/vscode-server-linux-x64.tar.gz_$#cmprs#$/vscode-server-linux-x64/out/vs/server/node/server.cli.js",
    size: 164894,
    creationDate: 1725697333755,
    lastModifiedDate: 1689182004000,
    abstractContent: "/*!--------------------------------------------------------\n * Copyright (C) Microsoft Corporation. All rights reserved.\n *--------------------------------------------------------*/(function(){var u1=",
    highlightContent: '0,mode:_});const t1=<mark class="search-result-highlight">await</mark> m(v);for(const e1 of t1)<mark class="search-result-highlight">await</mark>',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785734866,
  },
  {
    id: "r0bY0JEBP3pVznhigIWT",
    index: "samed_index",
    filename: "ptyHostMain",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/diff-files/vscode-server-linux-x64.tar.gz_$#cmprs#$/vscode-server-linux-x64/out/vs/platform/terminal/node/ptyHostMain.js",
    size: 389478,
    creationDate: 1725697333745,
    lastModifiedDate: 1689182004000,
    abstractContent: "/*!--------------------------------------------------------\n * Copyright (C) Microsoft Corporation. All rights reserved.\n *--------------------------------------------------------*/(function(){var oe=",
    highlightContent: '`Assertion <mark class="search-result-highlight">failed</mark> (${o})`:"Assertion <mark class="search-result-highlight">Failed</mark>")}e.ok=',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785734687,
  },
  {
    id: "rkbY0JEBP3pVznhigIUE",
    index: "samed_index",
    filename: "watcherMain.nls",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/diff-files/vscode-server-linux-x64.tar.gz_$#cmprs#$/vscode-server-linux-x64/out/vs/platform/files/node/watcher/watcherMain.nls.js",
    size: 846,
    creationDate: 1725697333727,
    lastModifiedDate: 1689182004000,
    abstractContent: '/*!--------------------------------------------------------\n * Copyright (C) Microsoft Corporation. All rights reserved.\n *--------------------------------------------------------*/define("vs/platform',
    highlightContent: 'Please consult the log for more <mark class="search-result-highlight">details</mark>.","{0} ({1}',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785734581,
  },
  {
    id: "rUbY0JEBP3pVznhif4Xj",
    index: "samed_index",
    filename: "bootstrap",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/diff-files/vscode-server-linux-x64.tar.gz_$#cmprs#$/vscode-server-linux-x64/out/bootstrap.js",
    size: 2410,
    creationDate: 1725697333723,
    lastModifiedDate: 1689180520000,
    abstractContent: '"use strict";(function(c,s){typeof exports=="object"?module.exports=s():c.MonacoBootstrap=s()})(this,function(){const c=typeof require=="function"?require("module"):void 0,s=typeof require=="function"',
    highlightContent: '"u"){console.warn("enableASARSupport() is only <mark class="search-result-highlight">available</mark>',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785734547,
  },
  {
    id: "qEbY0JEBP3pVznhifoWS",
    index: "samed_index",
    filename: "common_e96e9bea_1.0.0.min.css",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_e96e9bea_1.0.0.min.css.map",
    size: 1197079,
    creationDate: 1714303163095,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_e96e9bea_1.0.0.min.css","mappings":"AAsGE,gBCweF,CC9kBA,MAQI,qQAIA,sMAIA,iKAIA,sNAGF,2BACA,qBACA,6BACA,6BAMA,yMACA,mGACA,4EAOA,gDC4PI,wBALI,CDrPR,0BACA,0BACA,wBAIA,kBAIA,sB',
    highlightContent: '+<mark class="search-result-highlight">JAIA</mark>,kDAFF,SAGE,<mark class="search-result-highlight">CAIA</mark>,gOAEF,KAEE,iUAEF,<mark class="search-result-highlight">OAIE</mark>,<mark class="search-result-highlight">CAIA</mark>,wNAEF',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785734095,
  },
  {
    id: "p0bY0JEBP3pVznhifIUR",
    index: "samed_index",
    filename: "common_dcb821d8_1.0.0.min.js",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_dcb821d8_1.0.0.min.js.map",
    size: 1461298,
    creationDate: 1714303163067,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_dcb821d8_1.0.0.min.js","mappings":";iOAMA,MAAMA,UAA6B,YAIjCC,YAAYC,GACVC,MAAMD,GAER,KAAAE,QAAU,KACJC,KAAKH,MAAME,SAASC,KAAKH,MAAME,SAAS,EAE9C,KAAAE,oBAAsB,cAAiB,CAACJ,EAAOK',
    highlightContent: ',QAAY2H,<mark class="search-result-highlight">EAAIC</mark>,<mark class="search-result-highlight">EAAI18D</mark>,<mark class="search-result-highlight">EAAIC</mark>,<mark class="search-result-highlight">EAAIC</mark>,<mark class="search-result-highlight">EAAIC</mark>,<mark class="search-result-highlight">EAAI</mark>+6D,<mark class="search-result-highlight">EAAIC</mark>',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785733431,
  },
  {
    id: "pkbY0JEBP3pVznhieYXq",
    index: "samed_index",
    filename: "common_dcb821d8_1.0.0.min",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_dcb821d8_1.0.0.min.js",
    size: 412490,
    creationDate: 1714303163027,
    lastModifiedDate: 1669810924000,
    abstractContent: '/*! For license information please see common_dcb821d8_1.0.0.min.js.LICENSE.txt */\n"use strict";(self.webpackChunkjooya=self.webpackChunkjooya||[]).push([[719],{63893:(e,t,r)=>{r.d(t,{Z:()=>Pr});var a',
    highlightContent: '(<mark class="search-result-highlight">this.tail.next</mark>=e,e.prev=<mark class="search-result-highlight">this.tail</mark>,e.next=null,<mark class="search-result-highlight">this.tail</mark>',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["UTF-8"],"Content-Type":["text/plain; charset=UTF-8"]}',
    contentType: "text/plain",
    encoding: "UTF-8",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785732981,
  },
  {
    id: "pUbY0JEBP3pVznhieIWl",
    index: "samed_index",
    filename: "common_c030a089_1.0.0.min.js",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_c030a089_1.0.0.min.js.map",
    size: 807075,
    creationDate: 1714303162971,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_c030a089_1.0.0.min.js","mappings":"gKAiDWA,EAAoB,CAC7BC,MAAO,OACPC,YAAa,UAEJC,EAAyB,CAClCC,OAAQ,EACRC,WAAY,EACZC,iBAAkB,EAClBC,WAAY,EACZC,WAAY,EACZC,MAAO,EACPC,MAAO,GAGEC,G',
    highlightContent: '<mark class="search-result-highlight">EAAIK</mark>,EAER,<mark class="search-result-highlight">CAIA</mark>,IAAK,<mark class="search-result-highlight">IAAInpB</mark>,<mark class="search-result-highlight">EAAI</mark>,EAAGA,<mark class="search-result-highlight">EAAI</mark>,<mark class="search-result-highlight">GAAIA</mark>,',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785732617,
  },
  {
    id: "pEbY0JEBP3pVznhid4WK",
    index: "samed_index",
    filename: "common_c030a089_1.0.0.min",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_c030a089_1.0.0.min.js",
    size: 144832,
    creationDate: 1714303162939,
    lastModifiedDate: 1669810924000,
    abstractContent: '"use strict";(self.webpackChunkjooya=self.webpackChunkjooya||[]).push([[977],{47669:(e,t,i)=>{i.d(t,{N:()=>pe});var n=i(18299),a=i(35144),o=i(32234),r=i(93321),s={color:"fill",borderColor:"stroke"},l=',
    highlightContent: '(<mark class="search-result-highlight">this.hoverDataIdx</mark>=<mark class="search-result-highlight">this.findDataIndex</mark>(e,t))>=0:(<mark class="search-result-highlight">this.hoverDataIdx</mark>',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785732397,
  },
  {
    id: "o0bY0JEBP3pVznhidoWC",
    index: "samed_index",
    filename: "common_bfb9ab6b_1.0.0.min.js",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_bfb9ab6b_1.0.0.min.js.map",
    size: 1157155,
    creationDate: 1714303162915,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_bfb9ab6b_1.0.0.min.js","mappings":"0KA+CIA,GAAQ,UACL,SAASC,EAAiBC,GAE/B,MAAqB,aAAdA,EAAKC,KAoBd,SAA4BD,GAC1B,IAAIE,EAAaF,EAAKG,gBAClBC,EAASC,EAA2BL,EAAME,GAC9C,OAAQA,EAAWI,',
    highlightContent: 'F,EAAO,<mark class="search-result-highlight">IAAIsZ</mark>,EAAA,EAAa5d,<mark class="search-result-highlight">EAAI</mark>,<mark class="search-result-highlight">GAAIA</mark>,<mark class="search-result-highlight">EAAI</mark>,<mark class="search-result-highlight">GAAIzB</mark>,<mark class="search-result-highlight">EAAI</mark>',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785732036,
  },
  {
    id: "okbY0JEBP3pVznhidYUB",
    index: "samed_index",
    filename: "common_bfb9ab6b_1.0.0.min",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_bfb9ab6b_1.0.0.min.js",
    size: 205138,
    creationDate: 1714303162887,
    lastModifiedDate: 1669810924000,
    abstractContent: '"use strict";(self.webpackChunkjooya=self.webpackChunkjooya||[]).push([[425],{12950:(t,e,n)=>{n.d(e,{Z:()=>_});var i=n(33051),r=n(85669),o=n(80423),a=n(32234),s=n(97980),u=(0,a.Yf)();function l(t){ret',
    highlightContent: 'i.head&&(i.head=e),<mark class="search-result-highlight">i.tail</mark>&&<mark class="search-result-highlight">i.tail.pipe</mark>(e),<mark class="search-result-highlight">i.tail</mark>=e,',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785731743,
  },
  {
    id: "oUbY0JEBP3pVznhidIUD",
    index: "samed_index",
    filename: "common_bde52cb3_1.0.0.min.js",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_bde52cb3_1.0.0.min.js.map",
    size: 930257,
    creationDate: 1714303162867,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_bde52cb3_1.0.0.min.js","mappings":";yIAOA,MAAMA,EAAY,CAChBC,GAAI,CACFC,sBAEFC,GAAI,CACFD,uBAIJ,SACO,MACJE,KAAK,CACJJ,YACAK,IAAK,KACLC,YAAa,KAEbC,cAAc,EAEdC,cAAe,CACbC,aAAa,',
    highlightContent: ',<mark class="search-result-highlight">GAAI</mark>,<mark class="search-result-highlight">GAAI</mark>,<mark class="search-result-highlight">GAAI</mark>,<mark class="search-result-highlight">GAAI</mark>,<mark class="search-result-highlight">GAAI</mark>,<mark class="search-result-highlight">GAAI</mark>,<mark class="search-result-highlight">GAAI</mark>,<mark class="search-result-highlight">GAAI</mark>,<mark class="search-result-highlight">GAAI</mark>,IAC7DC',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785731420,
  },
  {
    id: "oEbY0JEBP3pVznhicoWh",
    index: "samed_index",
    filename: "common_bde52cb3_1.0.0.min",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_bde52cb3_1.0.0.min.js",
    size: 206713,
    creationDate: 1714303162839,
    lastModifiedDate: 1669810924000,
    abstractContent: '/*! For license information please see common_bde52cb3_1.0.0.min.js.LICENSE.txt */\n(self.webpackChunkjooya=self.webpackChunkjooya||[]).push([[498],{30411:(t,e,n)=>{"use strict";n.d(e,{Z:()=>a});var r=',
    highlightContent: '==<mark class="search-result-highlight">n.wait</mark>?',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785731134,
  },
  {
    id: "n0bY0JEBP3pVznhicYXH",
    index: "samed_index",
    filename: "common_ae17c089_1.0.0.min.js",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_ae17c089_1.0.0.min.js.map",
    size: 741948,
    creationDate: 1714303162819,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_ae17c089_1.0.0.min.js","mappings":";iJAgDO,SAASA,EAA6BC,EAAYC,GACvD,SAASC,EAAiBC,EAASC,GACjC,IAAIC,EAAgB,GAQpB,OAPAF,EAAQG,cAAc,CACpBC,SAAU,SACVC,QAASR,EACTS,MAAOL,IACN,SAA',
    highlightContent: ',<mark class="search-result-highlight">EAAIA</mark>,<mark class="search-result-highlight">EAAiB</mark>,<mark class="search-result-highlight">EAAI</mark>,<mark class="search-result-highlight">EAAIA</mark>,<mark class="search-result-highlight">EAAiB</mark>,<mark class="search-result-highlight">EAAI</mark>,<mark class="search-result-highlight">EAAI</mark>,CACpF,CAEA,',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785730865,
  },
  {
    id: "nkbY0JEBP3pVznhicIWE",
    index: "samed_index",
    filename: "common_ae17c089_1.0.0.min",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_ae17c089_1.0.0.min.js",
    size: 124148,
    creationDate: 1714303162787,
    lastModifiedDate: 1669810924000,
    abstractContent: '/*! For license information please see common_ae17c089_1.0.0.min.js.LICENSE.txt */\n"use strict";(self.webpackChunkjooya=self.webpackChunkjooya||[]).push([[470],{31891:(e,t,n)=>{n.d(t,{s:()=>l,y:()=>o}',
    highlightContent: '=<mark class="search-result-highlight">t.dataIndex</mark>?(0,r.kJ)(<mark class="search-result-highlight">t.dataIndex</mark>)?',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785730601,
  },
  {
    id: "nUbY0JEBP3pVznhib4WJ",
    index: "samed_index",
    filename: "common_8676cb57_1.0.0.min.js",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_8676cb57_1.0.0.min.js.map",
    size: 894159,
    creationDate: 1714303162775,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_8676cb57_1.0.0.min.js","mappings":"yKAuEA,SAASA,EAASC,EAAKC,GACrB,IAAIC,EAIJ,OAHA,KAAYD,GAAO,SAAUE,GACd,MAAbH,EAAIG,IAA+B,SAAdH,EAAIG,KAAqBD,GAAQ,EACxD,IACOA,CACT,CA2CA,IAA',
    highlightContent: ',GACTO,EAAGI,eAAe,<mark class="search-result-highlight">IAAI</mark>,<mark class="search-result-highlight">KAAiBpB</mark>,<mark class="search-result-highlight">IAI3C</mark>,<mark class="search-result-highlight">GAAIgB</mark>,<mark class="search-result-highlight">EAAI</mark>,CACN',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785730277,
  },
  {
    id: "nEbY0JEBP3pVznhiboVT",
    index: "samed_index",
    filename: "common_8676cb57_1.0.0.min",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_8676cb57_1.0.0.min.js",
    size: 171728,
    creationDate: 1714303162751,
    lastModifiedDate: 1669810924000,
    abstractContent: '"use strict";(self.webpackChunkjooya=self.webpackChunkjooya||[]).push([[806],{2935:(e,t,n)=>{n.d(t,{N:()=>O});var o=n(33051),i=n(18299),r=n(32234),a=n(98071),s=n(76172);function l(e,t){var n;return o.',
    highlightContent: '=<mark class="search-result-highlight">e.dataIndex</mark>&&(<mark class="search-result-highlight">e.dataIndexInside</mark>=<mark class="search-result-highlight">e.dataIndex</mark>,<mark class="search-result-highlight">e.dataIndex</mark>',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785730035,
  },
  {
    id: "m0bY0JEBP3pVznhibYVD",
    index: "samed_index",
    filename: "common_4afbb465_1.0.0.min.js",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_4afbb465_1.0.0.min.js.map",
    size: 1001368,
    creationDate: 1714303162727,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_4afbb465_1.0.0.min.js","mappings":";wFAWAA,EAAOC,QAAU,SAAkBC,EAAMC,GAIvC,GAHAA,EAAWA,EAASC,MAAM,KAAK,KAC/BF,GAAQA,GAEG,OAAO,EAElB,OAAQC,GACN,IAAK,OACL,IAAK,KACL,OAAgB,KAATD',
    highlightContent: ',<mark class="search-result-highlight">GAAI</mark>,WACJC,<mark class="search-result-highlight">GAAI</mark>,WACJC,<mark class="search-result-highlight">GAAI</mark>,WACJC,<mark class="search-result-highlight">GAAI</mark>,WACJC,<mark class="search-result-highlight">GAAI</mark>,WACJC',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785729684,
  },
  {
    id: "mkbY0JEBP3pVznhia4X_",
    index: "samed_index",
    filename: "common_4afbb465_1.0.0.min",
    extension: "js",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_4afbb465_1.0.0.min.js",
    size: 221511,
    creationDate: 1714303162699,
    lastModifiedDate: 1669810924000,
    abstractContent: '/*! For license information please see common_4afbb465_1.0.0.min.js.LICENSE.txt */\n"use strict";(self.webpackChunkjooya=self.webpackChunkjooya||[]).push([[662],{47418:e=>{e.exports=function(e,n){if(n=',
    highlightContent: 'M)return null;var I={<mark class="search-result-highlight">container:o</mark>,<mark class="search-result-highlight">containerPadding:l</mark>',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "en",
    insertToDB: 1725785729435,
  },
  {
    id: "mEbY0JEBP3pVznhiaoWw",
    index: "samed_index",
    filename: "common_27545368_1.0.0.min.js",
    extension: "map",
    filePath: "/home/user/Desktop/RCDAT Flash/Jooya Folder/ui/dist/common_27545368_1.0.0.min.js.map",
    size: 1339489,
    creationDate: 1714303162635,
    lastModifiedDate: 1669810924000,
    abstractContent: '{"version":3,"file":"common_27545368_1.0.0.min.js","mappings":";6FAEA,SAASA,EAAQC,GAAmV,OAAtOD,EAArD,mBAAXE,QAAoD,iBAApBA,OAAOC,SAAmC,SAAiBF,GAAO,cAAcA,CAAK,EAAsB,SAAiBA,GAAO,OAAOA,GAAyB,mBAAXC,QAAyBD',
    highlightContent: ',<mark class="search-result-highlight">EAIJ</mark>,<mark class="search-result-highlight">SAAiCN</mark>,GAAO,<mark class="search-result-highlight">GAAIA</mark>,GAAOA,<mark class="search-result-highlight">EAAIO</mark>,WAAc,OAAOP,EAAO',
    metadataDetail: '{"X-TIKA:Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"X-TIKA:Parsed-By-Full-Set":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.csv.TextAndCSVParser"],"Content-Encoding":["ISO-8859-1"],"Content-Type":["text/plain; charset=ISO-8859-1"]}',
    contentType: "text/plain",
    encoding: "ISO-8859-1",
    author: null,
    title: null,
    subject: null,
    isRead: null,
    hasPassword: false,
    language: "so",
    insertToDB: 1725785728991,
  },
];
